version: '3.8'
services:
  database:
    image: postgres:15-alpine
    volumes:
      - db:/data/postgres
    ports:
      - 5433:5432
    networks:
      - db
    environment:
      POSTGRES_PASSWORD: password
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s

networks:
  db:
    driver: bridge

volumes:
  db: